"""create tables

Revision ID: 37aca8a4d23e
Revises: 
Create Date: 2025-09-30 23:05:59.737196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37aca8a4d23e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('effect_text', sa.Text(), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('egg_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fling_power', sa.Integer(), nullable=True),
    sa.Column('fling_effect', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokedex_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('critical_rate', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_chance', sa.Integer(), nullable=True),
    sa.Column('effect_text', sa.Text(), nullable=True),
    sa.Column('contact', sa.Boolean(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_egg_groups',
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('egg_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['egg_group_id'], ['egg_groups.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('specie_id', 'egg_group_id')
    )
    op.create_table('pokemon_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sa.String(length=100), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_gender_ratio',
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('specie_id', 'gender_id')
    )
    op.create_table('regional_pokedex_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('pokedex_name', sa.String(length=50), nullable=False),
    sa.Column('entry_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specie_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_effectiveness',
    sa.Column('attack_type_id', sa.Integer(), nullable=False),
    sa.Column('defense_type_id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attack_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['defense_type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('attack_type_id', 'defense_type_id')
    )
    op.create_table('version_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('base_status',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('special_attack', sa.Integer(), nullable=False),
    sa.Column('special_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_table('evolutions',
    sa.Column('from_form_id', sa.Integer(), nullable=False),
    sa.Column('to_form_id', sa.Integer(), nullable=False),
    sa.Column('evolution_level', sa.Integer(), nullable=True),
    sa.Column('evolution_trigger', sa.String(length=50), nullable=True),
    sa.Column('evolution_condition', sa.String(length=255), nullable=True),
    sa.Column('evolution_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evolution_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['from_form_id'], ['pokemon_forms.id'], ),
    sa.ForeignKeyConstraint(['to_form_id'], ['pokemon_forms.id'], ),
    sa.PrimaryKeyConstraint('from_form_id', 'to_form_id')
    )
    op.create_table('form_abilities',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.id'], ),
    sa.PrimaryKeyConstraint('form_id', 'ability_id')
    )
    op.create_table('form_moves',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('version_group_id', sa.Integer(), nullable=False),
    sa.Column('move_learn_method', sa.String(length=50), nullable=False),
    sa.Column('level_learned_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['version_group_id'], ['version_groups.id'], ),
    sa.PrimaryKeyConstraint('form_id', 'move_id', 'version_group_id')
    )
    op.create_table('form_types',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('form_id', 'type_id')
    )
    op.create_table('item_flavor_texts',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('version_group_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['version_group_id'], ['version_groups.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'version_group_id')
    )
    op.create_table('item_machines',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('version_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['version_group_id'], ['version_groups.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'move_id', 'version_group_id')
    )
    op.create_table('pokemon_sprites',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('is_shiny', sa.Boolean(), nullable=False),
    sa.Column('front_sprite', sa.String(length=255), nullable=True),
    sa.Column('back_sprite', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['pokemon_forms.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.PrimaryKeyConstraint('form_id', 'gender_id', 'is_shiny'),
    sa.UniqueConstraint('form_id', 'gender_id', 'is_shiny', name='uq_form_gender_shiny')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_sprites')
    op.drop_table('item_machines')
    op.drop_table('item_flavor_texts')
    op.drop_table('form_types')
    op.drop_table('form_moves')
    op.drop_table('form_abilities')
    op.drop_table('evolutions')
    op.drop_table('base_status')
    op.drop_table('version_groups')
    op.drop_table('type_effectiveness')
    op.drop_table('regional_pokedex_numbers')
    op.drop_table('pokemon_gender_ratio')
    op.drop_table('pokemon_forms')
    op.drop_table('pokemon_egg_groups')
    op.drop_table('moves')
    op.drop_table('types')
    op.drop_table('pokemon_species')
    op.drop_table('items')
    op.drop_table('generations')
    op.drop_table('genders')
    op.drop_table('egg_groups')
    op.drop_table('abilities')
    # ### end Alembic commands ###
